apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/pacman
    repoURL: 'https://code.immerda.ch/technat/digitalocean_doks_demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
